import type { TaskItem } from "./types";

export const initialTasks: TaskItem[] = [
  { id: "TASK-1038", title: "Review missing operative note", subtitle: "Somchai Srisuk · VIS-260715-091", workflow: "Missing Evidence", priority: "Critical", assignee: "Chatrapee Jam-Oum", assigneeInitials: "CJ", due: "Today, 14:30", dueTone: "rose", status: "In Progress", tab: "mine", description: "Operative note is required before the claim evidence package can be finalized." },
  { id: "TASK-1041", title: "Validate medication interaction warning", subtitle: "Nisa Wongchai · VIS-260715-104", workflow: "Prescription Safety", priority: "Critical", assignee: "Pharmacist Team", assigneeInitials: "PT", due: "Today, 15:00", dueTone: "rose", status: "Open", tab: "mine", description: "Potential drug interaction requires pharmacist review before dispensing." },
  { id: "TASK-1029", title: "Reconcile diagnosis and ICD-10 mismatch", subtitle: "Preecha Kittisak · VIS-260714-288", workflow: "Claim Readiness", priority: "High", assignee: "Dr. Narin", assigneeInitials: "DN", due: "Today, 16:00", dueTone: "amber", status: "In Review", tab: "mine", description: "Clinical diagnosis text does not fully align with the selected ICD-10 code." },
  { id: "TASK-1044", title: "Approve access exception request", subtitle: "Admin Governance · User U-0188", workflow: "Compliance", priority: "High", assignee: "Unassigned", assigneeInitials: "—", due: "Tomorrow, 09:00", dueTone: "slate", status: "Open", tab: "unassigned", description: "Temporary elevated access request requires compliance review and approval." },
  { id: "TASK-1035", title: "Complete medical certificate evidence", subtitle: "Malee Nopparat · VIS-260715-066", workflow: "Missing Evidence", priority: "Medium", assignee: "Chatrapee Jam-Oum", assigneeInitials: "CJ", due: "Tomorrow, 11:30", dueTone: "slate", status: "Open", tab: "mine", description: "Medical certificate is currently in draft and missing provider signature." },
  { id: "TASK-1017", title: "Review cost outlier justification", subtitle: "Kanya Meesuk · VIS-260713-177", workflow: "Claim Readiness", priority: "Medium", assignee: "Unassigned", assigneeInitials: "—", due: "Overdue 1 day", dueTone: "rose", status: "Overdue", tab: "overdue", description: "Visit cost exceeds the payer benchmark and requires clinical justification." },
  { id: "TASK-1008", title: "Confirm consent document version", subtitle: "PDPA Review · Patient P-00918", workflow: "Compliance", priority: "Low", assignee: "Chatrapee Jam-Oum", assigneeInitials: "CJ", due: "Jul 18, 17:00", dueTone: "slate", status: "Open", tab: "mine", description: "Verify that the latest PDPA consent template was used for this patient." },
  { id: "TASK-0996", title: "Clinical summary human review", subtitle: "Anon Yindee · VIS-260712-039", workflow: "Clinical Review", priority: "Low", assignee: "Dr. Narin", assigneeInitials: "DN", due: "Completed", dueTone: "emerald", status: "Completed", tab: "completed", description: "AI-generated clinical summary was reviewed and approved by the physician." },
];
