export type PayerStatus = "active" | "needs_review" | "draft" | "simulation" | "inactive";
export type ApprovalStatus = "draft" | "pending_approval" | "approved" | "active" | "rejected";
export type CoverageStatus = "likely_covered" | "need_review" | "not_covered";
export type ReadinessStatus = "ready" | "needs_review" | "not_ready" | "pending_evidence";
export type RiskLevel = "low" | "medium" | "high" | "critical";
export type UserRole = "admin" | "product_owner" | "rule_owner" | "claim_reviewer" | "compliance" | "auditor" | "executive";

export type Payer = { id: string; name: string; code: string; status: PayerStatus; defaultRuleSetId: string };
export type RuleSetSummary = { id: string; payerId: string; name: string; version: string; status: ApprovalStatus; updatedBy: string; updatedAt: string };
export type EvidenceRuleKey = "soap_note" | "diagnosis" | "icd10" | "icd9_procedure" | "prescription" | "medical_certificate" | "attachments" | "claim_summary" | "cost_justification";
export type EvidenceRequirement = "required" | "required_if" | "recommended" | "optional";
export type EvidenceRule = { key: EvidenceRuleKey; label: string; enabled: boolean; requirement: EvidenceRequirement; condition: string; readinessImpact: number };
export type IcdRules = { requireIcd10: boolean; requireIcd9ForProcedures: boolean; missingIcdAction: "block" | "warn"; diagnosisIcdConsistency: boolean; highRiskGroups: string[]; excludedGroups: string[]; humanReview: boolean };
export type CoverageRules = { defaultStatus: CoverageStatus; waitingPeriodSimulation: boolean; benefitLimit: number; exclusions: string[]; requiredEvidence: string[]; humanReview: boolean };
export type CostRules = { expectedMinimum: number; expectedMaximum: number; alertThreshold: number; blockThreshold: number; justificationThreshold: number; currency: "THB" | "USD" };
export type RiskRule = { key: string; label: string; enabled: boolean; riskLevel: RiskLevel; resultingStatus: ReadinessStatus; humanReview: boolean };
export type PayerRuleFormValues = {
  payerName: string;
  payerCode: string;
  status: PayerStatus;
  ruleSetName: string;
  effectiveDate: string;
  governanceOwner: string;
  description: string;
  evidenceRules: EvidenceRule[];
  icdRules: IcdRules;
  coverageRules: CoverageRules;
  costRules: CostRules;
  riskRules: RiskRule[];
  advancedNotes: string;
};
export type RuleSetDetail = RuleSetSummary & { form: PayerRuleFormValues };
export type ImpactMetric = { key: string; label: string; before: number; after: number; unit: "%" | "cases" | "score"; lowerIsBetter: boolean };
export type AiRecommendation = { id: string; title: string; missingEvidencePattern: string; predictedClaimImpact: string; costInsight: string; confidence: number; evidenceBasis: string; generatedAt: string };
export type AffectedCase = { id: string; hn: string; visitId: string; patientNameMasked: string; payer: string; ruleSet: string; readinessScore: number; status: ReadinessStatus; coverage: CoverageStatus; risk: RiskLevel; missingEvidence: string[]; ruleFailures: string[]; costStatus: "normal" | "alert" | "blocked"; updatedAt: string };
export type VersionHistory = { version: string; changeSummary: string; changedBy: string; changedAt: string; approvalStatus: ApprovalStatus };
export type AuditEvent = { id: string; event: string; actor: string; role: string; timestamp: string; version: string; outcome: "success" | "warning" | "blocked"; phiStatus: "no_phi" | "masked" | "restricted" };
export type SimulationResult = { status: "idle" | "running" | "completed" | "failed"; caseId?: string; visitId?: string; passedRules: string[]; failedRules: string[]; readinessScore: number; coverage: CoverageStatus; risk: RiskLevel; missingEvidence: string[]; costImpact: string; humanReviewRequired: boolean };
export type PayerRulePermissions = { canEdit: boolean; canSimulate: boolean; canExport: boolean; canRequestApproval: boolean; canActivate: boolean; readOnlyReason?: string };
